data = [
 {"name": "Instagram", "followers_m": 691, "profession": "Social media platform", "country": "United States"},
 {"name": "Cristiano Ronaldo", "followers_m": 652, "profession": "Footballer", "country": "Portugal"},
 {"name": "Lionel Messi", "followers_m": 505, "profession": "Footballer", "country": "Argentina"},
 {"name": "Selena Gomez", "followers_m": 421, "profession": "Singer, Actress", "country": "United States"},
 {"name": "Dwayne Johnson", "followers_m": 394, "profession": "Actor, Producer, Wrestler", "country": "United States"},
 {"name": "Kylie Jenner", "followers_m": 393, "profession": "Reality TV Star, Businesswoman", "country": "United States"},
 {"name": "Ariana Grande", "followers_m": 375, "profession": "Singer, Actress", "country": "United States"},
 {"name": "Kim Kardashian West", "followers_m": 357, "profession": "Reality TV Star, Businesswoman", "country": "United States"},
 {"name": "Beyoncé", "followers_m": 311, "profession": "Singer, Actress", "country": "United States"},
 {"name": "Khloé Kardashian", "followers_m": 303, "profession": "Reality TV Star, Businesswoman", "country": "United States"},
 {"name": "Nike", "followers_m": 300, "profession": "Sportswear Brand", "country": "United States"},
 {"name": "Justin Bieber", "followers_m": 294, "profession": "Singer", "country": "Canada"},
 {"name": "Kendall Jenner", "followers_m": 288, "profession": "Model, Reality TV Star", "country": "United States"},
 {"name": "Taylor Swift", "followers_m": 281, "profession": "Singer", "country": "United States"},
 {"name": "National Geographic", "followers_m": 278, "profession": "Magazine", "country": "United States"},
 {"name": "Virat Kohli", "followers_m": 271, "profession": "Cricketer", "country": "India"},
 {"name": "Jennifer Lopez", "followers_m": 248, "profession": "Singer, Actress", "country": "United States"},
 {"name": "Neymar", "followers_m": 229, "profession": "Footballer", "country": "Brazil"},
 {"name": "Nicki Minaj", "followers_m": 225, "profession": "Rapper, Songwriter", "country": "Trinidad and Tobago / United States"},
 {"name": "Kourtney Kardashian", "followers_m": 219, "profession": "Reality TV Star, Businesswoman", "country": "United States"},
 {"name": "Miley Cyrus", "followers_m": 212, "profession": "Singer, Actress", "country": "United States"},
 {"name": "Katy Perry", "followers_m": 204, "profession": "Singer", "country": "United States"},
 {"name": "Zendaya", "followers_m": 179, "profession": "Actress, Singer", "country": "United States"},
 {"name": "Kevin Hart", "followers_m": 177, "profession": "Comedian, Actor", "country": "United States"},
 {"name": "Real Madrid CF", "followers_m": 173, "profession": "Football Club", "country": "Spain"},
 {"name": "Cardi B", "followers_m": 163, "profession": "Rapper, Actress", "country": "United States"},
 {"name": "LeBron James", "followers_m": 159, "profession": "Basketball Player", "country": "United States"},
 {"name": "Demi Lovato", "followers_m": 153, "profession": "Singer, Actress", "country": "United States"},
 {"name": "Rihanna", "followers_m": 149, "profession": "Singer, Businesswoman", "country": "Barbados"},
 {"name": "Chris Brown", "followers_m": 144, "profession": "Singer", "country": "United States"},
 {"name": "Drake", "followers_m": 142, "profession": "Rapper, Singer", "country": "Canada"},
 {"name": "FC Barcelona", "followers_m": 137, "profession": "Football Club", "country": "Spain"},
 {"name": "Ellen DeGeneres", "followers_m": 136, "profession": "Comedian, TV Host", "country": "United States"},
 {"name": "Billie Eilish", "followers_m": 124, "profession": "Singer", "country": "United States"},
 {"name": "Kylian Mbappé", "followers_m": 123, "profession": "a Footballer", "country": "France"},
 {"name": "UEFA Champions League", "followers_m": 120, "profession": "a Football Competition", "country": "Europe"},
 {"name": "Gal Gadot", "followers_m": 108, "profession": "a Actress", "country": "Israel"},
 {"name": "Lisa (BLACKPINK)", "followers_m": 105, "profession": "Singer, Dancer", "country": "Thailand / South Korea"},
 {"name": "Vin Diesel", "followers_m": 103, "profession": "a Actor", "country": "United States"},
 {"name": "NASA", "followers_m": 97, "profession": "a Space Agency", "country": "United States"},
 {"name": "Shraddha Kapoor", "followers_m": 94, "profession": "a Actress", "country": "India"},
 {"name": "Narendra Modi", "followers_m": 93, "profession": "the Prime Minister", "country": "India"},
 {"name": "Priyanka Chopra", "followers_m": 92, "profession": "Actress, Singer", "country": "India / United States"},
 {"name": "Shakira", "followers_m": 92, "profession": "Singer", "country": "Colombia"},
 {"name": "NBA", "followers_m": 90, "profession": "Basketball League", "country": "United States"},
 {"name": "Snoop Dogg", "followers_m": 88, "profession": "Rapper", "country": "United States"},
 {"name": "David Beckham", "followers_m": 88, "profession": "Former Footballer", "country": "United Kingdom"},
 {"name": "Dua Lipa", "followers_m": 87, "profession": "Singer", "country": "United Kingdom"},
 {"name": "Jennie (BLACKPINK)", "followers_m": 87, "profession": "Singer", "country": "South Korea"},
 {"name": "Alia Bhatt", "followers_m": 86, "profession": "Actress, Singer", "country": "India"}
]
